### ISSUE TITLE
Does Houdini Engine work with libHoudiniUI-dependent DSO plugins?

### ISSUE THREAD

**Issue by davvid** [sideeffects/HoudiniEngineForMaya#10]
HoudiniEngine currently uses `HOUDINI_DSO_EXCLUDE_PATH` to exclude `ROP_OpenGL`, `VEX_OpRender`, `SHOP_OGL`, and other DSO plugins that have a dependency on `libHoudinioUI`.

The behavior I've observed is: if a DSO plugin links against `HoudiniUI`, then that plugin will crash HoudiniEngine on startup.

* Is it true that HoudiniEngine does not support `HoudiniUI`-dependent plugins?
* Is support for render hooks and `HoudiniUI`-dependent plugins planned for the future?

I can document these details in the README once I've gotten confirmation from y'all on whether this is a known limitation, or possibly an environmental issue on my side.

I'm testing with Houdini 16.0.600 and Maya 2018 on Linux (RHEL7) in case that helps. Thank you!

**Comment by andrewkww** [comment]
The issue with Houdini Engine loading UI libraries is that it would conflict with Maya's Qt libraries. And those Houdini DSOs are excluded to avoid pulling in the UI dependencies.

This should only be an issue when using in-process backend though. If the backend is loaded with out-of-process backends (named pipe or socket), then it should be possible to load those excluded DSOs, and load in the UI libraries.

By render hooks, do you mean having Houdini material overriding shading in the Maya viewport? There's no plan for that at the moment. Houdini's viewport rendering works very differently than Maya's, which makes it quite difficult to have shaders that work in both viewports.

**Comment by davvid** [comment]
Thanks for confirming -- I wanted to make sure that the behavior I was observing was as intended.  I'll open a PR to mention why these plugins are excluded, and I'll close this issue in the PR's commit message.  I had to rediscover the "why" part myself, so figured that I should document it.  Thanks!
