### ISSUE TITLE
Asset.C(784): error C2039: 'cookTemplatedGeos' : is not a member of 'HAPI_CookOptions'

### ISSUE THREAD

**Issue by madjestic** [sideeffects/HoudiniEngineForMaya#5]
Asset.C(784): error C2039: 'cookTemplatedGeos' : is not a member of 'HAPI_CookOptions'

Perhaps I don't exactly know what I am doing, but I get this compiler error, and from the looks of it,  it's not due to my code or paths.

**Comment by ttvd** [comment]
Update your Houdini. 'cookTemplatedGeos' has been added to HAPI_CookOptions to help decide whether to recursively cook all templated geos or not. This has been added in late March.

**Comment by andrewkww** [comment]
As ttvd said, that's a recent addition. You need to build against a more recent Houdini version (at least 14.0.285 or 13.0.728).

**Comment by andrewkww** [comment]
If you prefer to stick with your version of Houdini, you could also checkout an older copy of the code. You can find which commit you need by looking at:
- https://github.com/sideeffects/HoudiniEngineForMaya/commits/Houdini14.0/HoudiniVersion
- https://github.com/sideeffects/HoudiniEngineForMaya/commits/Houdini13.0/HoudiniVersion

For example, if you have Houdini 14.0.294, then you'll want the commit before the next bump, which is 14.0.296.
i.e. 6f27c2cb718345728e46d82f5fe1ab970da52776^ which is equivalent to ab744c28d4ee497b98dee285375cb3fa469c32ce

**Comment by madjestic** [comment]
Thanks, will do.
