### ISSUE TITLE
InputCurve.C: error conversion from ‘HAPI_TransformEuler*’ to non-scalar type ‘HAPI_TransformEuler’ requested

### ISSUE THREAD

**Issue by ruchitinfushion** [sideeffects/HoudiniEngineForMaya#6]
Hi,
i m using HoudiniEngineForMaya source with Houdini13.0 branch to compile for Maya2016 with Houdini 13.0.376

Here is error code
`[~/Documents/houdiniEngineForMaya/build] - make
Scanning dependencies of target HoudiniEngine

[  4%] Building CXX object src/CMakeFiles/HoudiniEngine.dir/InputCurve.C.o
<command-line>: error: macro names must be identifiers

../Documents/houdiniEngineForMaya/src/InputCurve.C: In constructor ‘InputCurve::InputCurve(int, int)’:
../Documents/houdiniEngineForMaya/src/InputCurve.C:20: error: ‘HAPI_STATUS_CALL_RESULT’ was not declared in this scope
../Documents/houdiniEngineForMaya/src/InputCurve.C:20: error: ‘HAPI_STATUSVERBOSITY_ERRORS’ was not declared in this scope
../Documents/houdiniEngineForMaya/src/InputCurve.C: In member function ‘virtual void InputCurve::setInputTransform(MDataHandle&)’:
../Documents/houdiniEngineForMaya/src/InputCurve.C:53: error: conversion from ‘HAPI_TransformEuler*’ to non-scalar type ‘HAPI_TransformEuler’ requested

make[2]: **\* [src/CMakeFiles/HoudiniEngine.dir/InputCurve.C.o] Error 1
make[1]: **\* [src/CMakeFiles/HoudiniEngine.dir/all] Error 2
make: **\* [all] Error 2`

**Comment by andrewkww** [comment]
The API change was made in Houdini 13.0.467, and isn't compatible with your Houdini version.
If you want to use the latest 13.0 source, then it's best that you update your Houdini 13.0 to the latest build.

**Comment by ruchitinfushion** [comment]
Same for 14.0.395 also ??

I also tried  with 14.0.395 with Houdini14.0 branch and got below error.

```
<command-line>: error: macro names must be identifiers
make[2]: *** [src/CMakeFiles/HoudiniEngine.dir/InputCurve.C.o] Error 1
make[1]: *** [src/CMakeFiles/HoudiniEngine.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by andrewkww** [comment]
Yeah. Either use the latest Houdini 14.0 build with the latest code, or use an older revision of the code if you want to use an older 14.0 build.

**Comment by ruchitinfushion** [comment]
ok, Thanx much for info..
Can i get link for older source code ?? i did search in this repository but didn't found anything.

**Comment by andrewkww** [comment]
In each branch's commits, there are commits for version bump. You'd want to get the _last_ commit before the bump to the next version.
For Houdini 14.0.395, you'd want to build with b18951763af6be741ad2b0ebd6c7ccfd35dfaaaa.
